### ISSUE TITLE
Cannot login to Jenkins

### ISSUE THREAD

**Issue by dlogan** [CellProfiler/jenkins#3]
I need to check why cellprofile.org is not updating, but cannot login to Jenkins to peek:

```
imgbuild is missing the Overall/Read permission
```

![screen shot 2015-10-05 at 12 58 58 pm](https://cloud.githubusercontent.com/assets/1225595/10287436/ea8edcf6-6b60-11e5-9b30-b0d0b5041825.png)

**Comment by LeeKamentsky** [comment]
working on it - trying to remove security as indicated here: https://wiki.jenkins-ci.org/display/JENKINS/Disable+security

**Comment by LeeKamentsky** [comment]
Try now. Seems to have worked after reboot.

**Comment by dlogan** [comment]
Yup working, thanks!
